[tool.poetry]
name = "static-site-generator"
version = "0.1.0"
description = ""
authors = ["eva"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
ipython = "^8.26.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
